from django.urls import path
from django.contrib import admin
from . import views
from .views import (ProductList, ProductDetail, ProfileList, ProfileDetail,
                    ShippingAddressList, ShippingAddressDetail, OrderItemList,
                    OrderItemDetail, OrderList, OrderDetail, Vent_PhotoList,
                    Vent_PhotoDetail, PhotoList, PhotoDetail, DoctorVentList,
                    DoctorVentDetail,   AccessoriesDogsList,
                    AccessoriesDogsDetail, BedsDogsList, BedsDogsDetail, FoodDogsList,
                    FoodDogsDetail, FleaTicksDogsList, FleaTicksDogsDetail, 
                    GroomingDogsList, GroomingDogsDetail, PharmacyVitaminsDogsList,
                    PharmacyVitaminsDogsDetail, ToysDogsList, ToysDogsDetail, 
                    TreatsBiscuitsDogsList, TreatsBiscuitsDogsDetail, WetFoodDogsList,
                    WetFoodDogsDetail, AccessoriesCatsList, AccessoriesCatsDetail,
                    BedsCatsList, BedsCatsDetail, FoodCatsList, FoodCatsDetail,
                    FleaTicksCatsList, FleaTicksCatsDetail, GroomingcatsList, 
                    GroomingcatsDetail, ToyscatsList, ToyscatsDetail, 
                    TreatsBiscuitsCatsList, TreatsBiscuitsCatsDetail, 
                     CatsSerializer, FishSerializer, AccessoriesFishList,
                    AccessoriesFishDetail, FoodFishList, FoodFishDetail, BridList,
                    BridDetail, AccessoriesBridList, AccessoriesBridDetail , WetFoodCatsSerializer ,
                    WetFoodCatsDetail ,product_search ,
                    searchList ,searchDetail,FoodBridlist,
                    FoodBridDetail,Dogslist,DogsDetail)

urlpatterns = [
    path('',views.home,name = 'home'),
    path('product-detail/<slug:slug>',views.productDetailList,name = 'product-detailList'),
    path('product-detail/',views.productDetail,name = 'product-detail'),
    path('login',views.login,name = 'login'),
    path('signup',views.signup,name = 'signup'),
    path('checkout',views.checkout,name = 'checkout'),
    path('card',views.card,name = 'card'),
    path('add-product',views.addProduct,name = 'add-product'),
    path('products',views.product,name = 'products'),
    path('product/<str:types>',views.product_types,name = 'product-sp'),
    path('seller',views.seller,name = 'seller'),
    path('DashBoard',views.dashBoard,name = 'DashBoard'),
    path('logout',views.logoutUser,name = 'logout'),
    path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),
    path('doctor-sign',views.Doctor_signUP,name='doctor-sign' ),
    path('search_products',views.search_products,name='search_products'),
    path('product_detail',views.product_detail,name='product_detail'),
    path('products/', ProductList.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    path('profiles/', ProfileList.as_view(), name='profile_list'),
    path('profiles/<int:pk>/', ProfileDetail.as_view(), name='profile_detail'),
    path('shipping-addresses/', ShippingAddressList.as_view(), name='shipping_address_list'),
    path('shipping-addresses/<int:pk>/', ShippingAddressDetail.as_view(), name='shipping_address_detail'),
    path('order-items/', OrderItemList.as_view(), name='order_item_list'),
    path('order-items/<int:pk>/', OrderItemDetail.as_view(), name='order_item_detail'),
    path('orders/', OrderList.as_view(), name='order_list'),
    path('orders/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('vent-photos/', Vent_PhotoList.as_view(), name='vent_photo_list'),
    path('vent-photos/<int:pk>/', Vent_PhotoDetail.as_view(), name='vent_photo_detail'),
    path('photos/', PhotoList.as_view(), name='photo_list'),
    path('photos/<int:pk>/', PhotoDetail.as_view(), name='photo_detail'),
    path('doctor-vents/', DoctorVentList.as_view(), name='doctor_vent_list'),
    path('doctor-vents/<int:pk>/', DoctorVentDetail.as_view(), name='doctor_vent_detail'),
    path('search/', searchList.as_view(), name='search_list'),
    path('search/<int:pk>/', searchDetail.as_view(), name='search_detail'),
    path('accessories-dogs/', AccessoriesDogsList.as_view(), name='accessories_dogs_list'),
    path('accessories-dogs/<int:pk>/', AccessoriesDogsDetail.as_view(), name='accessories_dogs_detail'),
    path('beds-dogs/', BedsDogsList.as_view(), name='beds_dogs_list'),
    path('beds-dogs/<int:pk>/', BedsDogsDetail.as_view(), name='beds_dogs_detail'),
    path('food-dogs/', FoodDogsList.as_view(), name='food_dogs_list'),
    path('food-dogs/<int:pk>/', FoodDogsDetail.as_view(), name='food_dogs_detail'),
    path('flea-ticks-dogs/', FleaTicksDogsList.as_view(), name='flea_ticks_dogs_list'),
    path('flea-ticks-dogs/<int:pk>/', FleaTicksDogsDetail.as_view(), name='flea_ticks_dogs_detail'),
    path('grooming-dogs/', GroomingDogsList.as_view(), name='grooming_dogs_list'),
    path('grooming-dogs/<int:pk>/', GroomingDogsDetail.as_view(), name='grooming_dogs_detail'),
    path('pharmacy-vitamins-dogs/', PharmacyVitaminsDogsList.as_view(), name='pharmacy_vitamins_dogs_list'),
    path('pharmacy-vitamins-dogs/<int:pk>/', PharmacyVitaminsDogsDetail.as_view(), name='pharmacy_vitamins_dogs_detail'),
    path('toys-dogs/', ToysDogsList.as_view(), name='toys_dogs_list'),
    path('toys-dogs/<int:pk>/', ToysDogsDetail.as_view(), name='toys_dogs_detail'),
    path('treats-biscuits-dogs/', TreatsBiscuitsDogsList.as_view(), name='treats_biscuits_dogs_list'),
    path('treats-biscuits-dogs/<int:pk>/', TreatsBiscuitsDogsDetail.as_view(), name='treats_biscuits_dogs_detail'),   
    path('wet-food-dogs/', WetFoodDogsList.as_view(), name='wet_food_dogs_list'),
    path('wet-food-dogs/<int:pk>/', WetFoodDogsDetail.as_view(), name='wet_food_dogs_detail'),   
    path('accessories-cats/', AccessoriesCatsList.as_view(), name='accessories_cats_list'),
    path('accessories-cats/<int:pk>/', AccessoriesCatsDetail.as_view(), name='accessories_cats_detail'),
    path('beds-cats/', BedsCatsList.as_view(), name='beds_cats_list'),
    path('beds-cats/<int:pk>/', BedsCatsDetail.as_view(), name='beds_cats_detail'),
    path('food-cats/', FoodCatsList.as_view(), name='food_cats_list'),
    path('food-cats/<int:pk>/', FoodCatsDetail.as_view(), name='food_cats_detail'),
    path('flea-ticks-cats/', FleaTicksCatsList.as_view(), name='flea_ticks_cats_list'),
    path('flea-ticks-cats/<int:pk>/', FleaTicksCatsDetail.as_view(), name='flea_ticks_cats_detail'),
    path('grooming-cats/', GroomingcatsList.as_view(), name='grooming_cats_list'),
    path('grooming-cats/<int:pk>/', GroomingcatsDetail.as_view(), name='grooming_cats_detail'),
    path('toys-cats/', ToyscatsList.as_view(), name='toys_cats_list'),
    path('toys-cats/<int:pk>/', ToyscatsDetail.as_view(), name='toys_cats_detail'),
    path('treats-biscuits-cats/', TreatsBiscuitsCatsList.as_view(), name='treats_biscuits_cats_list'),
    path('treats-biscuits-cats/<int:pk>/', TreatsBiscuitsCatsDetail.as_view(), name='treats_biscuits_cats_detail'),
    path('wet-food-cats/', WetFoodCatsSerializer.as_view(), name='wet_food_cats_list'),
    path('wet-food-cats/<int:pk>/', WetFoodCatsDetail.as_view(), name='wet_food_cats_detail'),
    path('cats/', CatsSerializer.as_view(), name='cats_serializer'),
    path('fish/', FishSerializer.as_view(), name='fish_serializer'),
    path('birds/', BridList.as_view(), name='brid_list'),
    path('birds/<int:pk>/', BridDetail.as_view(), name='brid_detail'),
    path('accessories-birds/', AccessoriesBridList.as_view(), name='accessories_birds_list'),
    path('accessories-birds/<int:pk>/', AccessoriesBridDetail.as_view(), name='accessories_birds_detail'),
    path('accessories-fish/', AccessoriesFishList.as_view(), name='accessories_fish_list'),
    path('accessories-fish/<int:pk>/', AccessoriesFishDetail.as_view(), name='accessories_fish_detail'),
    path('food-fish/', FoodFishList.as_view(), name='food_fish_list'),
    path('food-fish/<int:pk>/', FoodFishDetail.as_view(), name='food_fish_detail'),
    path('search/', product_search, name='product_search_api'),
    path('search_api',views.search_api, name='search_api'),
    path('FoodBridlist',FoodBridlist.as_view(),name='FoodBridlist'),
    path('FoodBridDetail',FoodBridDetail.as_view(),name='FoodBridDetail'),
    path('Dogslist',Dogslist.as_view(),name='Dogslist'),
    path('DogsDetail',DogsDetail.as_view(),name='DogsDetail'),
]