# Generated by Django 4.2.2 on 2023-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.CharField(max_length=100)),
                ('Beds', models.CharField(max_length=100)),
                ('Food', models.CharField(max_length=100)),
                ('flea_ticks', models.CharField(max_length=100)),
                ('grooming', models.CharField(max_length=100)),
                ('Pharmacy_vitamins', models.CharField(max_length=100)),
                ('toys', models.CharField(max_length=100)),
                ('treats_biscuits', models.CharField(max_length=100)),
                ('wet_food', models.CharField(max_length=100)),
            ],
        ),
    ]
